//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaMedico.vista.admin
{


    public partial class GestionUsuarios
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// btnMostrarCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnMostrarCrear;

        /// <summary>
        /// pnlNotificacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotificacion;

        /// <summary>
        /// litNotificacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litNotificacion;

        /// <summary>
        /// txtBusqueda control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBusqueda;

        /// <summary>
        /// ddlRolFiltro control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRolFiltro;

        /// <summary>
        /// ddlEstadoFiltro control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstadoFiltro;

        /// <summary>
        /// btnBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// btnLimpiar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// lblTotalUsuarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalUsuarios;

        /// <summary>
        /// lblTotalDoctores control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalDoctores;

        /// <summary>
        /// lblTotalPacientes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalPacientes;

        /// <summary>
        /// lblTotalActivos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalActivos;

        /// <summary>
        /// gvUsuarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvUsuarios;

        /// <summary>
        /// pnlEmptyState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmptyState;

        /// <summary>
        /// hdnUsuarioSeleccionado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnUsuarioSeleccionado;

        /// <summary>
        /// hdnMostrarModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnMostrarModal;

        /// <summary>
        /// hdnAccionModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnAccionModal;

        /// <summary>
        /// lblErrorCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorCrear;

        /// <summary>
        /// txtNombreCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombreCrear;

        /// <summary>
        /// txtApellidoCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellidoCrear;

        /// <summary>
        /// txtEmailCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmailCrear;

        /// <summary>
        /// txtTelefonoCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTelefonoCrear;

        /// <summary>
        /// ddlRolCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRolCrear;

        /// <summary>
        /// txtDocumentoCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDocumentoCrear;

        /// <summary>
        /// txtPasswordCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPasswordCrear;

        /// <summary>
        /// ddlGeneroCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlGeneroCrear;

        /// <summary>
        /// txtFechaNacimientoCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaNacimientoCrear;

        /// <summary>
        /// ddlEspecialidadCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEspecialidadCrear;

        /// <summary>
        /// txtColegiaturaCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtColegiaturaCrear;

        /// <summary>
        /// txtExperienciaCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExperienciaCrear;

        /// <summary>
        /// txtPesoPacienteCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPesoPacienteCrear;

        /// <summary>
        /// txtFechaReferenciaPacienteCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaReferenciaPacienteCrear;

        /// <summary>
        /// btnCrearUsuario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCrearUsuario;

        /// <summary>
        /// lblErrorEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorEditar;

        /// <summary>
        /// txtNombreEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombreEditar;

        /// <summary>
        /// txtApellidoEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellidoEditar;

        /// <summary>
        /// txtEmailEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmailEditar;

        /// <summary>
        /// txtTelefonoEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTelefonoEditar;

        /// <summary>
        /// ddlRolEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRolEditar;

        /// <summary>
        /// txtDocumentoEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDocumentoEditar;

        /// <summary>
        /// ddlGeneroEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlGeneroEditar;

        /// <summary>
        /// txtFechaNacimientoEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaNacimientoEditar;

        /// <summary>
        /// ddlEspecialidadEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEspecialidadEditar;

        /// <summary>
        /// txtColegiaturaEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtColegiaturaEditar;

        /// <summary>
        /// txtExperienciaEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtExperienciaEditar;

        /// <summary>
        /// txtPesoPacienteEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPesoPacienteEditar;

        /// <summary>
        /// txtFechaReferenciaPacienteEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaReferenciaPacienteEditar;

        /// <summary>
        /// chkActivoEditar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActivoEditar;

        /// <summary>
        /// btnGuardarCambios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardarCambios;

        /// <summary>
        /// lblMensajeConfirmacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensajeConfirmacion;

        /// <summary>
        /// btnConfirmarAccion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarAccion;
    }
}

